### ISSUE TITLE
Dropped from Gentoo

### ISSUE THREAD

**Issue by rodarima** [dillo-browser/dillo#12]
We could merge the leftover patches and maybe ping Gentoo to keep it afloat.

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=98573254e171f5de8c91588ea39c4fa2f499e563

**Comment by Kangie** [comment]
Resolved!

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=b07732fc411f73372f4dda5241cbfe80c2cbfbf1

**Comment by rodarima** [comment]
Thanks! I'm happy to see it coming back to Gentoo.
