### ISSUE TITLE
bookmark sections' title lines look confusing

### ISSUE THREAD

**Issue by drawkula** [dillo-browser/dillo#127]
The titles of the bookmark sections look like progress bars.
Probably a side effect of their title length.

![image](https://github.com/dillo-browser/dillo/assets/9768622/1e17b35e-05b6-4eab-8d7d-558a61475cf6)

**Comment by drawkula** [comment]
Can (under some strange circumstances) `dpid` and the old `/opt/dillo/lib/dillo/dpi/bookmarks/bookmarks.dpi` have been still running?

Despite rebuilding several times I could not see the new bookmarks yesterday, gave up, but today I see a change without rebuilding.  In between the system only was suspended, not rebooted and since the last try where I still saw the old bookmarks there was no new rebuild/install.

I closed dillo again and still see...
```
$ ps U$USER | egrep 'dpi|dillo'
1281453 ?        S      0:00 dpid
1281454 ?        S      0:00 /opt/dillo/lib/dillo/dpi/bookmarks/bookmarks.dpi
1281604 pts/2    S+     0:00 grep -E dpi|dillo
```
Not waiting for a timeout or such now... killing them.

That's my best candidate for an explanation so far.

**Comment by rodarima** [comment]
> Can (under some strange circumstances) `dpid` and the old `/opt/dillo/lib/dillo/dpi/bookmarks/bookmarks.dpi` have been still running?

Yes, dpid keeps running for some time as well as the bookmarks.dpi (or any other *server* plugin recently used). To stop the daemon and the plugins you can use:

```
$ dpidc stop
```

Dillo will start dpid again next time and load the new plugins.
