### ISSUE TITLE
Please provide binaries

### ISSUE THREAD

**Issue by eugenialoli** [dillo-browser/dillo#157]
Thank you very much for resurrecting Dillo. I always loved this little browser! 

I understand that the main way to distribute Linux apps is via source (both for practical, and philosophical reasons), but it's going to be a long time since Dillo gets updated in most distros. The best way to get bug reports is for people to use the app by downloading an appimage (maybe the easiest to build?), or a flatpack (most difficult to build), a plain binary zip file, or an rpm/deb package. I personally want to try Dillo very much, but I don't really feel like building it from source. I used to build apps under linux in the early 2000s a lot, but I've made a point in recent years of not wanting to do that anymore. It's inconvenient, and archaic.

**Comment by rodarima** [comment]
Duplicated of https://github.com/dillo-browser/dillo/issues/152.
