### ISSUE TITLE
Add support for relative reference URLs

### ISSUE THREAD

**Issue by rodarima** [dillo-browser/dillo#195]
Example in duckduckgo:

```html
<link rel="stylesheet" media="handheld, all" href="//duckduckgo.com/dist/lr.7ea0bec6b92cbc81590a.css" type="text/css"/>
```

Should load the stylesheet using the same scheme as the current page. See https://www.rfc-editor.org/rfc/rfc3986#section-4.2

**Comment by rodarima** [comment]
Also: https://stackoverflow.com/a/4832046

> I could only find one that did not handle the protocol relative URL correctly: _an obscure *nix browser called Dillo_.

**Comment by louis77** [comment]
@rodarima Dillo resolves protocol-relative URLs, I've prepared an example here:
https://faq.emacs.ch/test.html

The reason that Dillo doesn't load the duckduckgo.com css above is, that the media type is "handheld". Dillo only loads media type "screen".

Can you verify this?

**Comment by rodarima** [comment]
Hi,

> @rodarima Dillo resolves protocol-relative URLs, I've prepared an 
> example here:
> https://faq.emacs.ch/test.html
> 
> The reason that Dillo doesn't load the duckduckgo.com css above is, 
> that the media type is "handheld". Dillo only loads media type 
> "screen".
> 
> Can you verify this?

Yeah it works fine, not sure how I came to that conclusion without 
testing it first :-)

Thanks for the test, we can close this now.
