### ISSUE TITLE
Configure uses `which` which is not POSIX compliant

### ISSUE THREAD

**Issue by Kangie** [dillo-browser/dillo#262]
## Issue

```
checking FLTK 1.3... yes
checking whether to link to X11... yes
checking for jpeglib.h... yes
checking for jpeg_destroy_decompress in -ljpeg... yes
checking for zlib.h... yes
checking for zlibVersion in -lz... yes
checking for libpng-config... ./configure: line 7202: which: command not found
./configure: line 7204: which: command not found
./configure: line 7207: which: command not found
```

`which` is not listed as a required command by POSIX and should be replaced by `command -v`.

See also: https://bugs.gentoo.org/940568

## Reproducing

Attempt to configure dillo on a machine without `which`.

## Resolution

Exorcise `which` from the codebase.

Examples:

https://github.com/dillo-browser/dillo/blob/4f303337cdf3d86b69918a137db19351cdbae581/autogen.sh#L18

https://github.com/dillo-browser/dillo/blob/4f303337cdf3d86b69918a137db19351cdbae581/configure.ac#L298-L313

**Comment by Kangie** [comment]
Re:

https://github.com/dillo-browser/dillo/blob/4f303337cdf3d86b69918a137db19351cdbae581/configure.ac#L298-L313

If autotools is to be retained this whole section (and the checks afterwards) could be trivially simplified to 'query pkg-config'.

**Comment by rodarima** [comment]
I commented on the meson build in the PR. Let's keep this issue to solve *only* the problem of removing `which` to `command -v`, which should be fairly easy to do.

We don't have a build dependency over `pkg-config`, so I don't think this particular problem needs to pull it.

**Comment by eli-schwartz** [comment]
Instead of using `command -v`, there is preexisting code earlier in this file:
```m4
AC_PATH_PROG(FLTK_CONFIG,fltk-config)
```

indicating the correct way to check for a program while respecting pre-set environment variables, is already known.

> We don't have a build dependency over `pkg-config`, so I don't think this particular problem needs to pull it.

"which" isn't the problem that is solved by using pkg-config. You still have to check for and find `pkg-config` as well.

The problem that is solved by using pkg-config is the cross-compilation problem. :) There are plenty of other dependencies that can use the same treatment... openssl, zlib, jpeg...

**Comment by eli-schwartz** [comment]
It's possible to check pkg-config first and fall back to foobar-config programs only when that fails.

**Comment by rodarima** [comment]
> ...indicating the correct way to check for a program...

The `which` command is not needed, so I prefer to switch to `command -v` which should be available in a POSIX shell.

> The problem that is solved by using pkg-config is the cross-compilation problem

Then I recommend you address it in another issue. I think this may also help #258 and #34. It would be nice to have a cross-compilation build in the CI, but I'm not sure if I know how to set it up.

**Comment by rodarima** [comment]
Fixed in https://github.com/dillo-browser/dillo/commit/9880c1ba603a6080b2493c7c399ae36d656a9834
