### ISSUE TITLE
Remove border from images with href

### ISSUE THREAD

**Issue by rodarima** [dillo-browser/dillo#270]
Rationale:

![img-border](https://github.com/user-attachments/assets/cc0add67-9e17-48f8-8d75-6830fdd9996b)

**Comment by ioc2e3** [comment]
> 理由：
> 
> ![img 邊框](https://private-user-images.githubusercontent.com/3866127/374313179-cc0add67-9e17-48f8-8d75-6830fdd9996b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzYxOTAsIm5iZiI6MTcyODY3NTg5MCwicGF0aCI6Ii8zODY2MTI3LzM3NDMxMzE3OS1jYzBhZGQ2Ny05ZTE3LTQ4ZjgtOGQ3NS02ODMwZmRkOTk5NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTk0NDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU2MjI4Y2VkNjE3YmExMzk3ZGQyNWJmNmZiMzAxOWRlZTljMGRiNWQ2NjM3YTI3YTZhMGQ0YmEyM2E1YmEyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.b1qhVAUKhssWi8_2TUmbWiuSXQ1UBem1zq5UOAGZEQY)

Have the same needs ...

.
