### ISSUE TITLE
Handset mode

### ISSUE THREAD

**Issue by sjehuda** [dillo-browser/dillo#296]
Good day!

I am using [postmarketOS](https://wiki.postmarketos.org/wiki/Dillo), and I have tried [Mobilized-Dillo](https://www.toomanyatoms.com/software/mobilized_dillo.html), yesterday.

Mobilized-Dillo is useful for handset devices, including displays with touch interface.

I think, that it would be beneficial to integrate features from Mobilized-Dillo into Dillo.

For larger touch screen devices, I use Falkon, because it offers touch interface, yet I would definitely prefer Dillo for handset devices that fit to a pocket.

Schimon

**Comment by rodarima** [comment]
> it would be beneficial to integrate features from Mobilized-Dillo into Dillo.

Yes, I'm aware. For now, I'm focusing on desktop. We may be able to join forces and have both implementations merged, but not likely happening soon.

**Comment by sjehuda** [comment]
Thank you! This is good to know.
