### ISSUE TITLE
XMPP PubSub

### ISSUE THREAD

**Issue by sjehuda** [dillo-browser/dillo#297]
Please add support for XMPP.

By adding support for XMPP, I namely mean to [Atom Over XMPP](https://blasta.woodpeckersnest.eu/help/about/xmpp/atomsub) (XEP-0277 and XEP-0472) which is utilizing XEP-0060: Publish-Subscribe (PubSub) which allows to host "rich" content on XMPP.

This is a visual demonstration to prove that subject matter https://video.xmpp-it.net/w/vNqcMooy3pqRAZ8Yb8grr1

[Rivista XJP](https://git.xmpp-it.net/sch/Rivista) is an HTTP gateway to deliver posts from the XMPP network.

See also:
- https://xmpp.org/extensions/xep-0060.html
- https://xmpp.org/extensions/xep-0277.html
- https://xmpp.org/extensions/xep-0472.html
- https://blasta.woodpeckersnest.eu/help/about/xmpp/pubsub
- https://join.movim.eu/

For example, the journal at https://mov.im/blog/edhelas is not hosted at mov.im; rather, it is hosted inside an account at XMPP server movim.eu which is conveyed by the Movim instance at mov.im.

Please join to JDev group chat if you want more help or information https://search.jabber.network/search?q=jdev

Related: https://github.com/crossbowerbt/dillo-plus/issues/54

**Comment by rodarima** [comment]
> [Rivista XJP](https://git.xmpp-it.net/sch/Rivista) is an HTTP gateway to deliver posts from the XMPP network.

What is wrong with this gateway?

**Comment by rodarima** [comment]
Yes, you can make a plugin in Python as long as you output HTML that Dillo can parse. See the available plugins as examples.

Maybe you use something like [miniflux](https://miniflux.app/) as a web reader interface, so you can just connect your gateway to miniflux and read the feeds from there via HTTP as HTML.

**Comment by sjehuda** [comment]
I will use Slixmpp to retrieve HTML content from XMPP PubSub nodes.

I suppose, that I will use my own design.

I will continue at the mailing list.

Thank you.
