### ISSUE TITLE
EVP_PKEY_get_id deprecated since openssl 3.0

### ISSUE THREAD

**Issue by th-otto** [dillo-browser/dillo#30]
That function was deprecated since openssl 3.0.0, and no longer exists in newer versions. Consequently i get a warning during compile, and a link error at runtime.

(sorry but i have no idea how to properly replace it)

System: openSUSE; with openssl 3.1.4 installed

**Comment by rodarima** [comment]
Can you paste the full error that you are getting? Following the documentation for OpenSSL 3.1, it seems to be supported:

https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_get_id.html

Also, which commit are you using? I changed the OpenSSL implementation recently.

**Comment by th-otto** [comment]
Oops sorry, you are right. I had both an older version installed (openssl 1.1.0) as well as openssl-3, but only development files for the older version, so that was used instead.

**Comment by rodarima** [comment]
I was planning to add support for OpenSSL 1.1 too, but for now only 3.x is supported. Anyway, this should be detected at configure time in any case. Thanks for the report :-)

**Comment by th-otto** [comment]
Yes, support for openssl 1.1 would be  nice, since i have no port of openssl3 for atari (yet) ;)

BTW, in your readme you mention that you have no control of dillo.org anymore, but the about:splash page still has links to it (and is rendered quite strangely)

**Comment by rodarima** [comment]
> Yes, support for openssl 1.1 would be nice, since i have no port of openssl3 for atari (yet) ;)

In the meanwhile, you can try with [mbedTLS](https://en.wikipedia.org/wiki/Mbed_TLS) in case it is already ported (use `--disable-openssl` to search only for mbedTLS).

> BTW, in your readme you mention that you have no control of dillo.org anymore, but the about:splash page still has links to it (and is rendered quite strangely)

Thanks, I opened #32 to address it.
