### ISSUE TITLE
Add support for WebP images

### ISSUE THREAD

**Issue by rodarima** [dillo-browser/dillo#71]
Similarly as for SVG images, support for WebP images would be nice.

Libraries from #53:
- https://chromium.googlesource.com/webm/libwebp

The test procedure is simple as we only need to generate a pair of images like PNG and WebP, and ensure the rendering is the same for both.

**Comment by MrMinderbinder** [comment]
SVG support sounds good, WebP not so much...

https://siipo.la/blog/is-webp-really-better-than-jpeg
https://eng.aurelienpierre.com/2021/10/webp-is-so-great-except-its-not/
https://www.jwz.org/blog/2023/09/webp-is-going-great/

**Comment by JessFairbairn** [comment]
Probably a separate bug but if and when webp or SVG support is added it would be worth adding support for the <picture> tag (assuming it isn't already sorted)
